---
title: "Putting the pieces together"
author: "Brendan Palmer"
date: "3 December 2018"
output:
  word_document: default
  html_document: default
---

# This is the beginning of the project

## Data overview
```{r packages and setup, include = FALSE}

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, 
                      fig.width  = 6, fig.height = 4)

# The clean data file is called within each of the plots and analysis scripts
# source("scripts/01_data_cleaning.R")

# To get the output to save in the docs folder use:
# rmarkdown::render('all_together.now', output_file = 'docs/example_project_report.docx') in the console
# If you just click the knit button, it will save alongside the Rmd file

# Load your packages here  
library(tidyverse)
library(stargazer)
```

```{r Plots, echo = FALSE}

source("scripts/02_plots.R")

# The location of the Rmd file dictates whether the path to other files is successful
who_ire
```

```{r Analysis, echo = FALSE}

source("scripts/01_data_cleaning.R")

who_ire <- who_tb_data %>%
  filter(country == "Ireland") %>%
  # Basic barplot with data by age shown
  ggplot() +
  geom_bar(mapping = aes(x = year, y = total, fill = age),
           stat = "identity") +
  labs(title = "Summary overview of all TB cases in Ireland", 
       x = "Year", y = "Total number of cases", fill = "Age group")

who_ire
```

